export const ADD_CART = 'ADD_CART'
export const CLEAR_ADD_CART = 'CLEAR_ADD_CART'
export const GET_CARTS = 'GET_CARTS'
export const DELETE_CART = 'DELETE_CART'
export const CLEAR_DELETE_CART = 'CLEAR_DELETE_CART'
