export const GET_JERSEYS = 'GET_JERSEYS'
export const GET_JERSEYS_BY_LEAGUE = 'GET_JERSEYS_BY_LEAGUE'
export const DELETE_PARAMETER_JERSEY = 'DELETE_PARAMETER_JERSEY'
export const SAVE_KEYWORD_JERSEY = 'SAVE_KEYWORD_JERSEY'
